# Generated by Django 5.1.4 on 2026-04-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentuser',
            name='aura',
            field=models.CharField(choices=[('MAXIMUM', 'Maximum'), ('MID', 'Mid'), ('LOW', 'Low')], default='MID', max_length=10),
        ),
    ]
