# Generated by Django 5.1.4 on 2026-04-27 12:45

import tokenbase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenbase', '0002_governmentuser_aura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentuser',
            name='government_id',
            field=models.CharField(default=tokenbase.models.generate_government_id, max_length=30, unique=True),
        ),
    ]
