# Generated by Django 5.2.13 on 2026-04-27 13:47

import tokenbase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenbase', '0003_alter_governmentuser_government_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='governmentuser',
            managers=[
                ('objects', tokenbase.models.GovernmentUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='governmentuser',
            name='role',
            field=models.CharField(choices=[('HR', 'Hr'), ('ADMIN', 'Admin'), ('RECRUITMENT', 'Recruitment')], default='ADMIN', max_length=30),
        ),
    ]
